### ISSUE TITLE
denoting a theta instead of individual params

### ISSUE THREAD

**Issue by fkrauer** [itsdfish/DifferentialEvolutionMCMC.jl#28]
Hi

I would like to use DifferentialEvolutionMCMC for fitting a complex ODE model (with DifferentialEquations). I like that the priors and the log-likelihood function are defined separately (opposed to for example Turing). However, if there are multiple parameters to be estimated, it seems a bit annoying to list each of them as a separate argument in the loglik function. Is there a way to have a theta vector as one argument, which is matched to the priors in the DE model? The following example (based on your example) does not work:
```
function loglik(θ, data)
    μ = θ[1]
    σ = θ[2]
    return sum(logpdf.(Normal(μ, σ), data))
end
```

returns
`ERROR: LoadError: MethodError: no method matching loglik(::Float64, ::Float64, ::Array{Float64,1})`

I assume the DE function expects n+1 arguments from the loglik function for a prior function with n parameters. Is there a way to adapt this?
Thanks, Fabienne

**Comment by itsdfish** [comment]
Hi,

I agree. That is not very convenient. Fortunately, I was able to allow a vector to be passed without too much trouble.  Rather than specifying each parameter, you can now use  `θ...` to map your parameters to a vector as follows:

```
function loglike(data, θ...)
    μ,σ = θ
    return sum(logpdf.(Normal(μ, σ), data))
end
```
A full example can be found [here](https://github.com/itsdfish/DifferentialEvolutionMCMC.jl/blob/master/Examples/Guassian_Example_Vector.jl).

**Comment by itsdfish** [comment]
My apologies. I did not realize that one of the tests is failing. Let me see if I can make it work with the new set up.

**Comment by itsdfish** [comment]
Ok. All fixed. The [new version](https://github.com/itsdfish/DifferentialEvolutionMCMC.jl/issues/30) should be released sometime today.

**Comment by fkrauer** [comment]
awesome, thanks!
