### ISSUE TITLE
official citation for DifferentialEvolutionMCMC

### ISSUE THREAD

**Issue by fkrauer** [itsdfish/DifferentialEvolutionMCMC.jl#40]
Hi @itsdfish 

I was wondering what the official citation for your library is (for scientific publications)? Does it have DOI?

**Comment by itsdfish** [comment]
Thanks for citing this package. I do not currently have a DOI, but I will try to create one later today or tomorrow. I am providing [this](https://guides.github.com/activities/citable-code/) link for future reference. I will update you as soon as it is setup.

**Comment by itsdfish** [comment]
@fkrauer, 

I created a DOI, which is listed in the README.
