### ISSUE TITLE
Calculation of Rhat and ESS

### ISSUE THREAD

**Issue by fkrauer** [itsdfish/DifferentialEvolutionMCMC.jl#50]
Hi

Is the calculation of rhat and ESS based on the chains with or without the burnin? Does it matter for the calculation whether I specify `discard_burnin=false` or `discard_burnin=true`? Thanks

**Comment by itsdfish** [comment]
MCMCChains calculates rhat and ess based on all samples in the chain object. So if you use `discard_burnin=false`, those calculations will include the burnin samples. If you leave the burnin samples for visual inspection of convergence, you can slice the chain to remove the burnin samples like so: `chain = burnin_chain[500:end, :, :]`

**Comment by fkrauer** [comment]
yes, that's what I suspected. Thanks!
